### PR TITLE
feat: convert to a standard npm package

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by bernd-wechner** [comment]
Awesome. Packaging is a learning space for me. Will review soon!

**Comment by bernd-wechner** [comment]
This looks great, and totally new to me (node packages). So I wonder if I can impose on you with a question or request? 

1. A weenie little commentary on the role each of these files plays in the packaging process, or as good a link to a page that provides such a neat digestible summary?
2. A tip on publication? As in, are the steps to publsh a Node package? As an example I underwnet the study on PyPi publication a while back and as I found nothing out there that was KISS, I wrote [one](https://dev.to/thumbone/publishing-a-python-package-what-i-wish-the-maze-of-tutorials-covered-1838). I wonder if something similar is out there for node packages and publishing (the bare essentials so to speak).

**Comment by Mister-Hope** [comment]
rollup is used for packing, see https://rollupjs.org/, it can provides tree-shaking. (Actually can be omitted and just use esbuild, but containing it on toolchain can benefit if source code changes).

Then we introduce esbuild to handle files tree-shaked by rollup, and we use `minify` to minify the output result, with `target` to ensure the output files supports these env:

```
     target: ["es2021", "chrome80", "safari14", "firefox78", "edge80"],
```

- For the minimum Node LTS (Node.js 16), it supports almost every es2021 features.
- Other target are browsers with minimum support version

For publishing, register an account at npmjs.com first, and use `npm login` to login locally, then use `pnpm publish` to publish package **after packing**. Suggest releasing a few 0.0.x versions to ensure the package works well downstream, then you can bump to `1.0.0`

**Comment by Mister-Hope** [comment]
I wil update this pr very soon!

**Comment by Mister-Hope** [comment]
Any update with this and the other?

**Comment by bernd-wechner** [comment]
Merged this for now, and will do a pull and play with it later. Been breakneck busy on other jobs. Do let me know if you got my email.

**Comment by Mister-Hope** [comment]
> Merged this for now, and will do a pull and play with it later. Been breakneck busy on other jobs. Do let me know if you got my email.

Yes, checked that just now, the email I associated with GitHub will receive tons of github notifications so I missed that. I am using my education email to contact mostly.

**Comment by bernd-wechner** [comment]
> I am using my education email to contact mostly.

Feel free to reply from that one ;-). Be nice to hear from you.

**Pull request merged**
